[pyinstaller]
script = "src/ui.py"
name = "Конвертер CSV-RDF"
onefile = true

datas = [
    { src = "config.json", dest = "." }
]

hiddenimports = [
    "main",
    "monitel_framework",
    "monitel_framework.config",
    "monitel_framework.files",
    "monitel_framework.logging",
    "monitel_framework.ui_base",
    "modules.hierarchy_parser",
    "modules.xml_generator"
]

paths = ["src"]

[build]
name = "Конвертер CSV-RDF"
version = "1.4.0"