# Конфигурация для PyInstaller (используется build.py)
[pyinstaller]
# Точка входа — ui.py в src/
script = "src/ui.py"

# Имя выходного .exe
name = "Конвертер CSV-RDF"

# Сборка в один файл
onefile = true

# Добавляем config.json в корень .exe
datas = [
    { src = "config.json", dest = "." }
]

# Явно указываем импорты, которые PyInstaller может не увидеть
hiddenimports = [
    # Основные модули приложения
    "main",
    "ui",
    "modules.hierarchy_parser",
    "modules.xml_generator",

    # Фреймворк
    "monitel_framework",
    "monitel_framework.config",
    "monitel_framework.files",
    "monitel_framework.logging",
    "monitel_framework.ui_base",

    # Зависимости
    "PyQt6",
    "PyQt6.QtWidgets",
    "PyQt6.QtCore",
    "PyQt6.QtGui"
]

# Пути для поиска модулей
paths = ["src"]

[build]
# Название продукта (для релизов)
name = "Конвертер CSV-RDF"

