name: 🧪 Тесты

on:
  push:
    branches: []
  pull_request:
    branches: []

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.11']

    steps:
      - name: 🔹 Checkout кода
        uses: actions/checkout@v4

      - name: 🔹 Установка Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 🔹 Установка зависимостей
        run: |
          pip install --upgrade pip
          pip install -e .  # Установка проекта в editable-режиме
          pip install pytest pytest-cov

      - name: 🔹 Запуск тестов с pytest
        run: |
          pytest --cov=src --cov-report=term --cov-report=xml

      - name: 🔹 Отправка отчёта о покрытии в Codecov (опционально)
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
